_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
SL_equivalent_sample_size:
    value: 10
prior_type:
    value: dirichlet
pseudo_counts:
    value: 1
